#!/bin/bash

# Check if folders or files exist and remove them
if [[ -e 'split' || -e '.img' || -e 'ramdisk' || -e 'AnyKernel.zip' ]]; then
    rm -rf split .img ramdisk AnyKernel.zip
    echo '[+] Workspace cleaned'
else
    echo '[!] Nothing to clean'
fi

# Delete kernel file inside AnyKernel3 folder if it exists
if [[ -e 'AnyKernel3/kernel' ]]; then
    rm 'AnyKernel3/Image'
    echo '[+] Kernel file deleted from AnyKernel3 folder'
fi


