#!/bin/bash

# Check if folders or files exist and remove them
if [[ -e 'split' || -e 'ramdisk' || -e 'AnyKernel.zip' || -e 'new-boot.img' ]]; then
    rm -rf split ramdisk AnyKernel.zip new-boot.img
    echo '[+] Workspace cleaned'
else
    echo '[!] Nothing to clean'
fi

# Delete kernel file inside AnyKernel3 folder if it exists
if [[ -e 'AnyKernel3/Image' ]]; then
    rm 'AnyKernel3/Image'
    echo '[+] Kernel file deleted from AnyKernel3 folder'
fi


